#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# SuperWeb Testing — Automated Setup & Run Script
# ─────────────────────────────────────────────────────────────
set -euo pipefail

# ── Defaults (override via env vars) ──────────────────────────
: "${SUPERWEB_TARGET_URL:=http://localhost:8081}"
: "${SUPERWEB_SOURCE_ROOT:=~/workspace/projects/loop_factory}"
: "${SUPERWEB_OUTPUT_DIR:=~/workspace/projects/loop_factory/superweb_output}"
: "${SUPERWEB_MODE:=agent}"           # scripted | agent
: "${SUPERWEB_LLM_URL:=http://pop-os:8080}"
: "${SUPERWEB_LLM_MODEL:=Qwen3.6-27B}"
: "${SUPERWEB_LLM_API_KEY:=not-needed}"
: "${SUPERWEB_VARIATIONS:=3}"
: "${SUPERWEB_DRY_RUN:=false}"
: "${SUPERWEB_HEADLESS:=true}"
: "${SUPERWEB_TIMEOUT_MS:=30000}"
: "${SUPERWEB_MAX_PAGES:=3}"
: "${SUPERWEB_LOG_TYPE:=docker}"
: "${SUPERWEB_LOG_CONTAINER:=loop_factory_web}"
: "${SUPERWEB_OPENHANDS_TIMEOUT:=2400}"   # agent mode only
: "${SUPERWEB_OPENHANDS_START:=true}"   # auto-start OH container in agent mode

# ── Colours ───────────────────────────────────────────────────
R='\033[0;31m'; G='\033[0;32m'; Y='\033[0;33m'; B='\033[0;34m'; NC='\033[0m'

info()  { echo -e "${B}[INFO]${NC}  $*"; }
warn()  { echo -e "${Y}[WARN]${NC}  $*"; }
ok()    { echo -e "${G}[OK]${NC}    $*"; }
fail()  { echo -e "${R}[FAIL]${NC}  $*"; exit 1; }

# ── Resolve script directory (portable) ──────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

info "SuperWeb Testing Pipeline"
info "Script dir: $SCRIPT_DIR"
info ""
info "Configuration:"
info "  Target URL       : $SUPERWEB_TARGET_URL"
info "  Source root      : $SUPERWEB_SOURCE_ROOT"
info "  Output dir       : $SUPERWEB_OUTPUT_DIR"
info "  Mode             : $SUPERWEB_MODE"
info "  LLM URL          : $SUPERWEB_LLM_URL"
info "  LLM Model        : $SUPERWEB_LLM_MODEL"
info "  Variations       : $SUPERWEB_VARIATIONS"
info "  Dry run          : $SUPERWEB_DRY_RUN"
info "  Browser headless : $SUPERWEB_HEADLESS"
info "  Log container    : $SUPERWEB_LOG_CONTAINER"
info ""

# ── Step 1: Check prerequisites ──────────────────────────────
info "Checking prerequisites..."

command -v python3 >/dev/null 2>&1 || fail "python3 not found"
command -v uv     >/dev/null 2>&1 || fail "uv not found — install from https://github.com/astral-sh/uv"

if [[ "$SUPERWEB_MODE" == "agent" ]]; then
    command -v docker >/dev/null 2>&1 || fail "docker required for agent mode"
    docker compose version >/dev/null 2>&1 || fail "docker compose v2 required"
fi

# ── Step 2: Install dependencies ──────────────────────────────
if [[ ! -d ".venv" ]]; then
    info "Creating virtual environment..."
    uv venv
fi

source .venv/bin/activate
info "Syncing dependencies..."
uv sync --quiet

# ── Step 3: Install Playwright browsers (scripted mode) ───────
if [[ "$SUPERWEB_MODE" == "scripted" ]]; then
    info "Checking Playwright browsers..."
    python -m playwright install chromium 2>/dev/null || warn "Playwright install failed (may already be installed)"
fi

# ── Step 4: Write config.yaml ──────────────────────────────────
info "Generating config.yaml..."
cat > config.yaml <<EOF
# Auto-generated by run_test.sh

llm:
  base_url: "$SUPERWEB_LLM_URL"
  model: "$SUPERWEB_LLM_MODEL"
  api_key: "$SUPERWEB_LLM_API_KEY"

target:
  url: "$SUPERWEB_TARGET_URL"
  scan_paths:
    - "/"
    - "/login"
    - "/register"

source:
  root: "$SUPERWEB_SOURCE_ROOT"
  form_patterns:
    - "**/forms.py"
    - "**/schemas.py"
    - "**/models.py"
    - "**/validators.py"
    - "**/*_form.py"
    - "**/schema*.py"
  route_patterns:
    - "**/routes.py"
    - "**/api.py"
    - "**/endpoints.py"

logs:
  type: "$SUPERWEB_LOG_TYPE"
  docker_container: "$SUPERWEB_LOG_CONTAINER"
  error_patterns:
    - "ERROR"
    - "Exception"
    - "Traceback"
    - "500"
    - "Connection refused"

browser:
  headless: $SUPERWEB_HEADLESS
  timeout_ms: $SUPERWEB_TIMEOUT_MS
  viewport:
    width: 1280
    height: 720

pipeline:
  data_variations: $SUPERWEB_VARIATIONS
  max_pages: $SUPERWEB_MAX_PAGES
  artifacts_dir: "./artifacts"
EOF
ok "config.yaml written"

# ── Step 5: Manage OpenHands container (agent mode) ──────────
if [[ "$SUPERWEB_MODE" == "agent" && "$SUPERWEB_OPENHANDS_START" == "true" ]]; then
    info "Starting OpenHands Agent Server..."
    LLM_BASE_URL="$SUPERWEB_LLM_URL" \
    LLM_MODEL="$SUPERWEB_LLM_MODEL" \
    docker compose -f compose.yaml up -d 2>&1 | grep -v "WARN\|deprecated" || true

    info "Waiting for health check..."
    for i in $(seq 1 30); do
        if curl -sf "http://localhost:3005/health" >/dev/null 2>&1; then
            ok "OpenHands is healthy"
            break
        fi
        sleep 2
    done

    if ! curl -sf "http://localhost:3005/health" >/dev/null 2>&1; then
        warn "OpenHands health check timed out — proceeding anyway"
    fi
fi

# ── Step 6: Build CLI arguments ──────────────────────────────
CLI_ARGS=(
    run
    --target "$SUPERWEB_TARGET_URL"
    --source "$SUPERWEB_SOURCE_ROOT"
    --output "$SUPERWEB_OUTPUT_DIR"
    --llm-url "$SUPERWEB_LLM_URL"
    --llm-model "$SUPERWEB_LLM_MODEL"
    --variations "$SUPERWEB_VARIATIONS"
    --mode "$SUPERWEB_MODE"
    --agent-timeout "$SUPERWEB_OPENHANDS_TIMEOUT"
)

if [[ "$SUPERWEB_DRY_RUN" == "true" ]]; then
    CLI_ARGS+=(--dry-run)
fi

# ── Step 7: Run the pipeline ──────────────────────────────────
info ""
info "Running pipeline: ${CLI_ARGS[*]}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if python -m src "${CLI_ARGS[@]}"; then
    ok ""
    ok "Pipeline complete."
    ok "Reports:"
    ok "  JSON: $SUPERWEB_OUTPUT_DIR/report/correlation_report.json"
    ok "  Markdown: $SUPERWEB_OUTPUT_DIR/report/summary.md"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
else
    fail "Pipeline exited with error"
fi

# ── Step 8: Cleanup OpenHands (optional) ──────────────────────
if [[ "$SUPERWEB_MODE" == "agent" && "${SUPERWEB_OPENHANDS_STOP:-false}" == "true" ]]; then
    info "Stopping OpenHands container..."
    docker compose -f compose.yaml down
    ok "OpenHands stopped"
fi